# CMake generated Testfile for 
# Source directory: /Users/cwbetts/makestuff/opensludge/libpng-1.6.30
# Build directory: /Users/cwbetts/makestuff/opensludge/libpng-1.6.30
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngtest "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngtest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngtest "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngtest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngtest "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngtest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngtest "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngtest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngtest.cmake")
else()
  add_test(pngtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-16-to-8 "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-16-to-8 "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-16-to-8 "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-16-to-8.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-16-to-8 "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-16-to-8.cmake")
else()
  add_test(pngvalid-gamma-16-to-8 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-background.cmake")
else()
  add_test(pngvalid-gamma-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
else()
  add_test(pngvalid-gamma-expand16-alpha-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-background.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-background "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-background.cmake")
else()
  add_test(pngvalid-gamma-expand16-background NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-expand16-transform.cmake")
else()
  add_test(pngvalid-gamma-expand16-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-sbit "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-sbit "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-sbit "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-sbit.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-sbit "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-sbit.cmake")
else()
  add_test(pngvalid-gamma-sbit NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-threshold "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-threshold "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-threshold "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-threshold.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-threshold "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-threshold.cmake")
else()
  add_test(pngvalid-gamma-threshold NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-gamma-transform.cmake")
else()
  add_test(pngvalid-gamma-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-interlace-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-interlace-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-interlace-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-interlace-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-interlace-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-interlace-standard.cmake")
else()
  add_test(pngvalid-progressive-interlace-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-size "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-size "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-size "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-size.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-size "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-size.cmake")
else()
  add_test(pngvalid-progressive-size NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-progressive-standard.cmake")
else()
  add_test(pngvalid-progressive-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-standard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-standard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-standard.cmake")
else()
  add_test(pngvalid-standard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-transform.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-transform "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngvalid" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngvalid-transform.cmake")
else()
  add_test(pngvalid-transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-none.cmake")
else()
  add_test(pngstest-1.8-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-1.8-alpha.cmake")
else()
  add_test(pngstest-1.8-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-none.cmake")
else()
  add_test(pngstest-linear-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-linear-alpha.cmake")
else()
  add_test(pngstest-linear-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-none.cmake")
else()
  add_test(pngstest-none-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-none-alpha.cmake")
else()
  add_test(pngstest-none-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-none.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-none "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-none.cmake")
else()
  add_test(pngstest-sRGB-none NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-alpha.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-alpha "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngstest" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngstest-sRGB-alpha.cmake")
else()
  add_test(pngstest-sRGB-alpha NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-discard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-discard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-discard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-discard.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-discard "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-discard.cmake")
else()
  add_test(pngunknown-discard NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-IDAT "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-IDAT "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-IDAT "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-IDAT.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-IDAT "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-IDAT.cmake")
else()
  add_test(pngunknown-IDAT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-if-safe "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-if-safe "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-if-safe "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-if-safe.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-if-safe "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-if-safe.cmake")
else()
  add_test(pngunknown-if-safe NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sAPI "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sAPI "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sAPI "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sAPI.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sAPI "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sAPI.cmake")
else()
  add_test(pngunknown-sAPI NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-save "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-save "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-save "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-save.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-save "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-save.cmake")
else()
  add_test(pngunknown-save NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sTER "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sTER "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sTER "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sTER.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sTER "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-sTER.cmake")
else()
  add_test(pngunknown-sTER NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-vpAg "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-vpAg "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-vpAg "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-vpAg.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-vpAg "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngunknown" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngunknown-vpAg.cmake")
else()
  add_test(pngunknown-vpAg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-quick "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-quick "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-quick "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-quick.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-quick "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-quick.cmake")
else()
  add_test(pngimage-quick NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-full "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Release/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-full "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/libpng16d.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/Debug/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-full "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/MinSizeRel/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-full.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-full "/opt/local/bin/cmake" "-DLIBPNG=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/libpng16.16.30.0.dylib" "-DTEST_COMMAND=/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/RelWithDebInfo/pngimage" "-P" "/Users/cwbetts/makestuff/opensludge/libpng-1.6.30/tests/pngimage-full.cmake")
else()
  add_test(pngimage-full NOT_AVAILABLE)
endif()
